"""empty message"""

revision = '183b2c5ef4f2'
down_revision = '0001_create_cv_pipeline_tables'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_document_sections',
    sa.Column('document_section_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('section_type', sa.String(length=100), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('start_char_index', sa.Integer(), nullable=True),
    sa.Column('end_char_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['candidate_documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_section_id'),
    sa.UniqueConstraint('document_id', 'section_order', name='uq_candidate_document_section_document_order')
    )
    op.create_index('idx_candidate_document_section_document_id', 'candidate_document_sections', ['document_id'], unique=False)
    op.create_index('idx_candidate_document_section_type', 'candidate_document_sections', ['section_type'], unique=False)
    op.create_index(op.f('ix_candidate_document_sections_document_section_id'), 'candidate_document_sections', ['document_section_id'], unique=False)
    op.create_index(op.f('ix_candidate_document_texts_document_text_id'), 'candidate_document_texts', ['document_text_id'], unique=False)
    op.alter_column('candidate_documents', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'indexing_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_candidate_documents_document_id'), 'candidate_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_candidate_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidate_documents_document_id'), table_name='candidate_documents')
    op.alter_column('candidate_documents', 'indexing_status',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('candidate_documents', 'processing_status',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_candidate_document_texts_document_text_id'), table_name='candidate_document_texts')
    op.drop_index(op.f('ix_candidate_document_sections_document_section_id'), table_name='candidate_document_sections')
    op.drop_index('idx_candidate_document_section_type', table_name='candidate_document_sections')
    op.drop_index('idx_candidate_document_section_document_id', table_name='candidate_document_sections')
    op.drop_table('candidate_document_sections')
    # ### end Alembic commands ###
